version: "3"
services:
  pwa-academy:
    container_name: "${CONTAINER_NAME}"
    image: "${IMAGE}"
    restart: always
    networks:
      - nginx_reverse_proxy

networks:
  nginx_reverse_proxy:
    external: true
    name: "nginx_reverse_proxy"
